# Generated by Django 3.0.9 on 2021-01-19 01:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ClienteSuscripcion',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comidas_consumidas', models.IntegerField(default=0)),
                ('fecha_inicio', models.DateField()),
                ('fecha_de_caducidad', models.DateField()),
                ('fecha_facturacion', models.DateField()),
                ('comidas_disponibles', models.IntegerField(default=0)),
                ('comidas_gratis_disponibles', models.IntegerField(default=0)),
                ('comidas_gratis_consumidas', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='TipoSuscripcion',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=350)),
                ('duracion', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='Suscripcion',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=200)),
                ('precio', models.FloatField()),
                ('cantidad_comidas', models.IntegerField(default=0)),
                ('comidas_gratis', models.IntegerField(default=0)),
                ('color', models.CharField(max_length=200)),
                ('id_tipo_suscripcion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='paquetes.TipoSuscripcion')),
            ],
        ),
    ]
