# Generated by Django 3.0.9 on 2021-01-19 01:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('general', '0002_perfil_id_cliente'),
        ('usuarios', '0001_initial'),
        ('calendario', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Categoria',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=200)),
                ('nombre_perfil', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='general.Perfil')),
            ],
        ),
        migrations.CreateModel(
            name='Comidas',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=200)),
                ('descripcion', models.CharField(max_length=200)),
                ('calorias_totales', models.FloatField()),
                ('macronutrientes', models.CharField(max_length=1000)),
                ('imagen', models.ImageField(upload_to='')),
                ('direccion_envio', models.CharField(max_length=500)),
                ('id_categoria', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='productos.Categoria')),
                ('id_vendedor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='usuarios.Vendedor')),
            ],
        ),
        migrations.CreateModel(
            name='Pedido',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_emitido', models.DateTimeField(verbose_name='Fecha de emisión')),
                ('estado', models.IntegerField(default=0)),
                ('id_cliente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='usuarios.Cliente')),
            ],
        ),
        migrations.CreateModel(
            name='DetallePedido',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_emitido', models.DateTimeField(verbose_name='Fecha de emisión')),
                ('hora_entrega', models.TimeField()),
                ('estado_pedido', models.IntegerField(default=0)),
                ('id_comida', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='productos.Comidas')),
                ('id_dias', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='calendario.Dias')),
                ('id_pedido', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='productos.Pedido')),
            ],
        ),
    ]
