# Generated by Django 3.0.9 on 2021-01-19 01:12

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Configuracion',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dolares_por_kilometros', models.FloatField()),
                ('valor_comida', models.FloatField()),
                ('direccion_fija', models.CharField(max_length=500)),
                ('no_comidas_por_semana', models.IntegerField(default=0)),
                ('no_de_comida_por_dia', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='Perfil',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=200)),
                ('peso_inicio', models.FloatField()),
                ('peso_meta', models.FloatField()),
            ],
        ),
    ]
