# Generated by Django 3.0.9 on 2021-01-19 01:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('usuarios', '0001_initial'),
        ('productos', '0001_initial'),
        ('calendario', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='detalle_dias',
            name='id_comida',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='productos.Comidas'),
        ),
        migrations.AddField(
            model_name='detalle_dias',
            name='id_dias',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='calendario.Dias'),
        ),
        migrations.AddField(
            model_name='calendario',
            name='id_cliente',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='usuarios.Cliente'),
        ),
    ]
