# Generated by Django 3.0.9 on 2021-01-19 01:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('paquetes', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='FormaDePago',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('forma_pago', models.CharField(max_length=250)),
            ],
        ),
        migrations.CreateModel(
            name='Iva',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('porcentaje', models.FloatField()),
                ('nombre_impuesto', models.CharField(max_length=300)),
            ],
        ),
        migrations.CreateModel(
            name='Tarjeta',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_propietario', models.CharField(max_length=200)),
                ('tipo_tarjeta', models.CharField(max_length=200)),
                ('fecha_caducidad', models.DateField()),
                ('direccion_facturacion', models.CharField(max_length=350)),
                ('cvv', models.IntegerField(default=0)),
                ('numero_tarjeta', models.CharField(max_length=16)),
            ],
        ),
        migrations.CreateModel(
            name='Factura',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('monto', models.FloatField()),
                ('id_forma_pago', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='seguridad.FormaDePago')),
                ('id_iva', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='seguridad.Iva')),
                ('id_suscripcion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='paquetes.Suscripcion')),
            ],
        ),
    ]
